# Generated by Django 5.1.2 on 2024-10-28 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devdb2024', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'managed': True, 'verbose_name': 'Водитель', 'verbose_name_plural': 'Водители'},
        ),
        migrations.AlterModelOptions(
            name='passenger',
            options={'managed': True, 'verbose_name': 'Пассажир', 'verbose_name_plural': 'Пассажиры'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'managed': True, 'verbose_name': 'Маршрут', 'verbose_name_plural': 'Маршруты'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'managed': True, 'verbose_name': 'Рейс', 'verbose_name_plural': 'Рейсы'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'managed': True, 'verbose_name': 'Билет', 'verbose_name_plural': 'Билеты'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'managed': True, 'verbose_name': 'Транспортное средство', 'verbose_name_plural': 'Транспортные средства'},
        ),
        migrations.AlterModelOptions(
            name='vehicletype',
            options={'managed': True, 'verbose_name_plural': 'Тип ТС'},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='driver_id',
            field=models.ForeignKey(db_column='driver_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='devdb2024.driver'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='route_id',
            field=models.ForeignKey(db_column='route_id', on_delete=django.db.models.deletion.DO_NOTHING, to='devdb2024.route'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='vin',
            field=models.ForeignKey(db_column='vin', on_delete=django.db.models.deletion.DO_NOTHING, to='devdb2024.vehicle'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='schedule_id',
            field=models.ForeignKey(db_column='schedule_id', on_delete=django.db.models.deletion.DO_NOTHING, to='devdb2024.schedule'),
        ),
    ]
