# Generated by Django 5.1.2 on 2024-10-31 21:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devdb2024', '0002_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'managed': True, 'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AddField(
            model_name='test',
            name='at_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='test',
            table='Test',
        ),
    ]
