# Generated by Django 5.1.2 on 2024-10-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devdb2024', '0002_alter_driver_options_alter_passenger_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int', models.IntegerField()),
            ],
            options={
                'db_table': 'Dat',
                'managed': True,
            },
        ),
    ]
