# Generated by Django 5.1.2 on 2024-11-01 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devdb2024', '0004_testtest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TestTest',
        ),
    ]
