# Generated by Django 5.1.2 on 2024-11-01 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_train_alternative', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
